name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "//docker.io/tayyabqaisar41514:${{ secrets.DOCKERPW }}" > ~/.docker/config.json

    - name: Build the Docker image
      run: docker build -t python-app .

    - name: Tag the Docker image
      run: docker tag python-app tayyabqaisar41514/python-auth-example1

    - name: Push the Docker image
      run: docker push tayyabqaisar41514/python-auth-example1
