name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t python-app .

    - name: Tag the Docker image
      run: docker tag python-app tayyabqaisar41514/python-auth-example1

    - name: Push the Docker image
      run: |
        echo "{\"auths\":{\"docker.io\":{\"username\":\"tayyabqaisar41514\",\"password\":\"${{ secrets.DOCKERHUB_TOKEN }}\",\"email\":\"tayyabqaisar41514@gmail.com\"}}}" > $HOME/.docker/config.json
        docker push tayyabqaisar41514/python-auth-example1
