name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERPW }} | docker login -u "tayyabqaisar41514" --password-stdin

    - name: Build the Docker image
      run: docker build -t python-app .

    - name: Tag the Docker image
      run: docker tag python-app tayyabqaisar41514/python-auth-example

    - name: Push the Docker image
      run: docker push tayyabqaisar41514/python-auth-example
