name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "tayyabqaisar41514" --password-stdin 
        docker build -t python-app .
        docker tag python-app tayyabqaisar41514/python-auth-example
        docker push tayyabqaisar41514/python-auth-example
